version: 2.0

jobs:
  build:
    docker:
      - image: scorpil/rust:nightly
    steps:
      - run:
          name: Dependencies
          command: apt-get update && apt-get install -qy git build-essential tree
      - checkout
      - run:
          name: Build
          command: cargo build
      - run:
          name: Test
          command: cargo test
